# CONFIGURACIÓN DEL SERVIDOR
spring.application.name=ms-contenedores
server.port=8080

# CONFIGURACIÓN DE POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/navium_contenedores
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN DE HIBERNATE (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave secreta para firmar y validar los JWT
jwt.secret=NaviumSecretKeyFirmaDeTokens!